Algoritmo "enquanto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Ricardo de Souza Silva 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/05/2021
Var

  x , soma : inteiro


Inicio

    escreva("Digiteo numero:")
     leia (x)
     
     enquanto x <> 0 faca
       soma<-soma + x
       escreva("Escreva novamente:")
       leia(X)
     fimenquanto
     
     escreval("Soma:", soma)


     
Fimalgoritmo
