Algoritmo "Problemafatorial"
// Disciplina   : [Linguagem e Lógica de Programação]
// Ricardo de Souza Silva
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/06/2021
Var
   i, n: inteiro
   soma: real



Inicio

   escreval("Digite o valor de N: ")
   leia(n)


   para i de n ate 1 faca

      escreval(i)
      soma<- i*n
      escreva(soma)
   fimpara



Fimalgoritmo