Algoritmo "sequencia_impares"
// Disciplina   : [Linguagem e Lógica de Programação]
// Ricardo de Souza Silva
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/06/2021
Var

  x, y, i : inteiro
  


Inicio

   escreva("Digite o valor de X:")
     leia(x)
     
    se x<0 entao
      y<- (x/x)+2

    
    fimse
   escreva(y)




Fimalgoritmo