Algoritmo "sequencia_impares"
// Disciplina   : [Linguagem e Lógica de Programação]
// Ricardo de Souza Silva
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/06/2021
Var



   x, y, i, soma : inteiro



Inicio

   escreva("Digite o valor de X: ")
   leia(x)

   soma<-0

   para i de 1 ate 4 faca

      soma <- soma + 2 + 1

      escreval(i, " = ", soma)


   fimpara




Fimalgoritmo