Algoritmo "tabuadaresolvida"
// Disciplina   : [Linguagem e Lógica de Programação]
// Ricardo de Souza Silva
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/06/2021
Var

   n, x, i, y: inteiro


Inicio
   escreva("Qual a tabuada?:")
   leia (n)

   escreva("Vezes quanto:")
   leia(y)


   para i de 1 ate y faca

      x<- i * n

      escreval(n ,"x",i ,"=",x)

   fimpara







Fimalgoritmo