Algoritmo "tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Ricardo de Souza Silva 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/06/2021
Var

    N, i, x, resultado : inteiro

Inicio



  escreva("Deseja a tabuada para qual valor? ")
   leia(N)

   para i de 1 ate 10 faca
      resultado <- i * N
      escreval(N, " x ", i, " = ", resultado)
   fimpara


Fimalgoritmo