Algoritmo "TrocadeValores"
// Disciplina   : [Linguagem e Lógica de Programação]
// Ricardo de Souza Silva
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/06/2021
Var

   a, b, troca : inteiro



Inicio


   escreva("Escreva A:")
   leia(a)
   escreva("Escreva B:")
   leia(b)

   se a<b entao
      troca<-b
      b<-a
      a<-troca
   fimse



Fimalgoritmo